  version: 2
  updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
      open-pull-requests-limit: 5
      labels:
        - "dependencies"
        - "github-actions"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "monday"
      open-pull-requests-limit: 10
      labels:
        - "dependencies"
      versioning-strategy: "increase"
      groups:
        production-dependencies:
          patterns:
            - "@mui/**"
            - "@radix-ui/**"
            - "react"
            - "react-dom"
            - "vite"
            - "vitest"
      commit-message:
        prefix: "chore(deps)"
