/**
 * @file 独家音乐资源数据配置
 * @description YYC³独家版权音乐、图片、视频资源配置
 * @author YYC³ Team
 * @version 1.0.0
 */

import type { MusicSong } from './types';

type MusicCategory = 'A' | 'B' | 'C' | 'D';

interface AlbumConfig {
  id: string;
  name: string;
  nameZh: string;
  description: string;
  cover: string;
  category: MusicCategory;
  year: number;
  songs: MusicSong[];
}

interface ArtistConfig {
  id: string;
  name: string;
  nameZh: string;
  avatar: string;
  bio: string;
  albums: string[];
}

interface VideoConfig {
  id: string;
  title: string;
  titleZh: string;
  thumbnail: string;
  videoUrl: string;
  duration: number;
  year: number;
}

interface PhotoConfig {
  id: string;
  title: string;
  imageUrl: string;
  year: number;
  category: 'portrait' | 'concert' | 'promo';
}

const LOGO_IMAGES: string[] = [
  '/D-Music/D-logo/D-logo-20.png',
  '/D-Music/D-logo/D-logo-21.png',
  '/D-Music/D-logo/D-logo-22.png',
  '/D-Music/D-logo/D-logo-23.png',
  '/D-Music/D-logo/D-logo-24.png',
  '/D-Music/D-logo/D-logo-25.png',
  '/D-Music/D-logo/D-logo-26.png',
  '/D-Music/D-logo/D-logo-27.png',
  '/D-Music/D-logo/D-logo-28.png',
  '/D-Music/D-logo/D-logo-29.png',
  '/D-Music/D-logo/D-logo-31.png',
  '/D-Music/D-logo/D-logo-32.png',
  '/D-Music/D-logo/D-logo-33.png',
  '/D-Music/D-logo/D-logo-34.png',
  '/D-Music/D-logo/D-logo-35.png',
  '/D-Music/D-logo/D-logo-36.png',
  '/D-Music/D-logo/D-logo-37.png',
  '/D-Music/D-logo/D-logo-38.png',
  '/D-Music/D-logo/D-logo-39.png',
  '/D-Music/D-logo/D-logo-49.png',
  '/D-Music/D-logo/D-logo-50.png',
  '/D-Music/D-logo/D-logo-51.png',
  '/D-Music/D-logo/D-logo-52.png',
  '/D-Music/D-logo/D-logo-53.png',
  '/D-Music/D-logo/D-logo-54.png',
  '/D-Music/D-logo/D-logo-55.png',
  '/D-Music/D-logo/D-logo-56.png',
  '/D-Music/D-logo/D-logo-57.png',
  '/D-Music/D-logo/D-logo-58.png',
  '/D-Music/D-logo/D-logo-59.png',
];

const PHOTOS: PhotoConfig[] = [
  { id: 'photo-1978', title: 'Music 1978', imageUrl: '/D-Music/D-98/Music-1978.jpg', year: 1978, category: 'portrait' },
  { id: 'photo-1979', title: 'Music 1979', imageUrl: '/D-Music/D-98/Music-1979.jpg', year: 1979, category: 'portrait' },
  { id: 'photo-1980', title: 'Music 1980', imageUrl: '/D-Music/D-98/Music-1980.jpg', year: 1980, category: 'portrait' },
  { id: 'photo-1981', title: 'Music 1981', imageUrl: '/D-Music/D-98/Music-1981.jpg', year: 1981, category: 'portrait' },
  { id: 'photo-1982', title: 'Music 1982', imageUrl: '/D-Music/D-98/Music-1982.jpg', year: 1982, category: 'portrait' },
  { id: 'photo-1983', title: 'Music 1983', imageUrl: '/D-Music/D-98/Music-1983.jpg', year: 1983, category: 'portrait' },
  { id: 'photo-1990', title: 'Music 1990', imageUrl: '/D-Music/D-98/Music-1990.jpg', year: 1990, category: 'concert' },
  { id: 'photo-1991', title: 'Music 1991', imageUrl: '/D-Music/D-98/Music-1991.jpg', year: 1991, category: 'concert' },
  { id: 'photo-1992', title: 'Music 1992', imageUrl: '/D-Music/D-98/Music-1992.jpg', year: 1992, category: 'concert' },
  { id: 'photo-1993', title: 'Music 1993', imageUrl: '/D-Music/D-98/Music-1993.jpg', year: 1993, category: 'promo' },
  { id: 'photo-1994', title: 'Music 1994', imageUrl: '/D-Music/D-98/Music-1994.jpg', year: 1994, category: 'promo' },
  { id: 'photo-1995', title: 'Music 1995', imageUrl: '/D-Music/D-98/Music-1995.jpg', year: 1995, category: 'promo' },
  { id: 'photo-1996', title: 'Music 1996', imageUrl: '/D-Music/D-98/Music-1996.jpg', year: 1996, category: 'promo' },
  { id: 'photo-1997', title: 'Music 1997', imageUrl: '/D-Music/D-98/Music-1997.jpg', year: 1997, category: 'promo' },
];

const VIDEOS: VideoConfig[] = [
  { id: 'video-1989', title: 'Music Video 1989', titleZh: '音乐视频 1989', thumbnail: '/D-Music/D-98/Music-1990.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1989.mp4', duration: 240, year: 1989 },
  { id: 'video-1990', title: 'Music Video 1990', titleZh: '音乐视频 1990', thumbnail: '/D-Music/D-98/Music-1990.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1990.mp4', duration: 260, year: 1990 },
  { id: 'video-1991', title: 'Music Video 1991', titleZh: '音乐视频 1991', thumbnail: '/D-Music/D-98/Music-1991.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1991.mp4', duration: 280, year: 1991 },
  { id: 'video-1992', title: 'Music Video 1992', titleZh: '音乐视频 1992', thumbnail: '/D-Music/D-98/Music-1992.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1992.mp4', duration: 300, year: 1992 },
  { id: 'video-1993', title: 'Music Video 1993', titleZh: '音乐视频 1993', thumbnail: '/D-Music/D-98/Music-1993.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1993.mp4', duration: 320, year: 1993 },
  { id: 'video-1994', title: 'Music Video 1994', titleZh: '音乐视频 1994', thumbnail: '/D-Music/D-98/Music-1994.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1994.mp4', duration: 340, year: 1994 },
  { id: 'video-1995', title: 'Music Video 1995', titleZh: '音乐视频 1995', thumbnail: '/D-Music/D-98/Music-1995.jpg', videoUrl: '/D-Music/D-98-Mp4/Music-1995.mp4', duration: 360, year: 1995 },
];

const ALBUM_A_SONGS: MusicSong[] = [
  {
    id: 'a-001',
    title: '那些年',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1978.jpg',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-A/那些年.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 85,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-002',
    title: '冬月里的生命之花',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1979.jpg',
    duration: 268,
    audioUrl: '/Music-Mp3/Music-A/冬月里的生命之花.mp3',
    genre: '民谣',
    mood: 'calm',
    bpm: 72,
    energy: 'low',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-003',
    title: '不过时间而已',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1980.jpg',
    duration: 312,
    audioUrl: '/Music-Mp3/Music-A/不过时间而已.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 90,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-004',
    title: '如梦的岁月',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1981.jpg',
    duration: 285,
    audioUrl: '/Music-Mp3/Music-A/如梦的岁月.mp3',
    genre: '抒情',
    mood: 'calm',
    bpm: 78,
    energy: 'low',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-005',
    title: '那如梦的岁月',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1982.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-A/那如梦的岁月.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 82,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-006',
    title: '岁月中丢失了年岁',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1983.jpg',
    duration: 332,
    audioUrl: '/Music-Mp3/Music-A/岁月中丢失了年岁.mp3',
    genre: '民谣',
    mood: 'melancholy',
    bpm: 68,
    energy: 'low',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-007',
    title: '一生一世的爱与陪伴',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1990.jpg',
    duration: 276,
    audioUrl: '/Music-Mp3/Music-A/一生一世的爱与陪伴.mp3',
    genre: '流行',
    mood: 'romantic',
    bpm: 88,
    energy: 'medium',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-008',
    title: '是你把自己弄丢了',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1991.jpg',
    duration: 295,
    audioUrl: '/Music-Mp3/Music-A/是你把自己弄丢了.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 92,
    energy: 'medium',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-009',
    title: '冬月里的季风',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1992.jpg',
    duration: 268,
    audioUrl: '/Music-Mp3/Music-A/冬月里的季风.mp3',
    genre: '民谣',
    mood: 'calm',
    bpm: 75,
    energy: 'low',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-010',
    title: '冬日里温暖的季风拂过她的脸',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1993.jpg',
    duration: 318,
    audioUrl: '/Music-Mp3/Music-A/冬日里温暖的季风拂过她的脸.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 80,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-011',
    title: '彼岸花的宿命',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1994.jpg',
    duration: 345,
    audioUrl: '/Music-Mp3/Music-A/彼岸花的宿命.mp3',
    genre: '古风',
    mood: 'melancholy',
    bpm: 70,
    energy: 'low',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-012',
    title: '雨季标本',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1995.jpg',
    duration: 288,
    audioUrl: '/Music-Mp3/Music-A/雨季标本.mp3',
    genre: '流行',
    mood: 'calm',
    bpm: 85,
    energy: 'low',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-013',
    title: '未曾守护的梦',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1996.jpg',
    duration: 312,
    audioUrl: '/Music-Mp3/Music-A/未曾守护的梦.mp3',
    genre: '抒情',
    mood: 'melancholy',
    bpm: 78,
    energy: 'medium',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'a-014',
    title: '辗转反侧的梦',
    artist: '董小姐',
    album: '岁月如歌',
    albumCover: '/D-Music/D-98/Music-1997.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-A/辗转反侧的梦.mp3',
    genre: '流行',
    mood: 'calm',
    bpm: 82,
    energy: 'low',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
];

const ALBUM_B_SONGS: MusicSong[] = [
  {
    id: 'b-001',
    title: '七秒之外',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1978.jpg',
    duration: 256,
    audioUrl: '/Music-Mp3/Music-B/七秒之外.mp3',
    genre: '流行',
    mood: 'energetic',
    bpm: 120,
    energy: 'high',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-002',
    title: '不过时间而已',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1979.jpg',
    duration: 305,
    audioUrl: '/Music-Mp3/Music-B/不过时间而已.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 88,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-003',
    title: '冬日暖阳',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1980.jpg',
    duration: 278,
    audioUrl: '/Music-Mp3/Music-B/冬日暖阳.mp3',
    genre: '抒情',
    mood: 'calm',
    bpm: 75,
    energy: 'low',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-004',
    title: '逐梦之路',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1981.jpg',
    duration: 322,
    audioUrl: '/Music-Mp3/Music-B/逐梦之路.mp3',
    genre: '励志',
    mood: 'energetic',
    bpm: 128,
    energy: 'high',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-005',
    title: '浮生似梦',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1982.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-B/浮生似梦.mp3',
    genre: '古风',
    mood: 'calm',
    bpm: 72,
    energy: 'low',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-006',
    title: '奈何彼岸花',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1983.jpg',
    duration: 345,
    audioUrl: '/Music-Mp3/Music-B/奈何彼岸花.mp3',
    genre: '古风',
    mood: 'melancholy',
    bpm: 68,
    energy: 'low',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-007',
    title: '岁月如歌',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1990.jpg',
    duration: 288,
    audioUrl: '/Music-Mp3/Music-B/岁月如歌.mp3',
    genre: '流行',
    mood: 'calm',
    bpm: 85,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-008',
    title: '只如初见若',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1991.jpg',
    duration: 312,
    audioUrl: '/Music-Mp3/Music-B/只如初见若.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 80,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-009',
    title: '浮生如渡',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1992.jpg',
    duration: 356,
    audioUrl: '/Music-Mp3/Music-B/浮生如渡.mp3',
    genre: '古风',
    mood: 'calm',
    bpm: 65,
    energy: 'low',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-010',
    title: '雨幕独白',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1993.jpg',
    duration: 278,
    audioUrl: '/Music-Mp3/Music-B/雨幕独白.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 90,
    energy: 'medium',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-011',
    title: '黎明的梦',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1994.jpg',
    duration: 302,
    audioUrl: '/Music-Mp3/Music-B/黎明的梦.mp3',
    genre: '抒情',
    mood: 'calm',
    bpm: 78,
    energy: 'low',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'b-012',
    title: '董小姐的祝福',
    artist: '董小姐',
    album: '浮生如渡',
    albumCover: '/D-Music/D-98/Music-1995.jpg',
    duration: 268,
    audioUrl: '/Music-Mp3/Music-B/董小姐的祝福.wav',
    genre: '流行',
    mood: 'happy',
    bpm: 95,
    energy: 'medium',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
];

const ALBUM_C_SONGS: MusicSong[] = [
  {
    id: 'c-001',
    title: '那些年',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1996.jpg',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-C/那些年.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 85,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-002',
    title: '不过时间而已',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1997.jpg',
    duration: 305,
    audioUrl: '/Music-Mp3/Music-C/不过时间而已.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 88,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-003',
    title: '若只如初见',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1978.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-C/若只如初见.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 82,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-004',
    title: '若善良真的已消失不见',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1979.jpg',
    duration: 345,
    audioUrl: '/Music-Mp3/Music-C/若善良真的已消失不见.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 75,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-005',
    title: '热血摇滚',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1980.jpg',
    duration: 278,
    audioUrl: '/Music-Mp3/Music-C/热血摇滚.mp3',
    genre: '摇滚',
    mood: 'energetic',
    bpm: 145,
    energy: 'high',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-006',
    title: '男人的难',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1981.jpg',
    duration: 322,
    audioUrl: '/Music-Mp3/Music-C/男人的难.mp3',
    genre: '民谣',
    mood: 'melancholy',
    bpm: 78,
    energy: 'medium',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-007',
    title: '未曾守护的梦',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1982.jpg',
    duration: 312,
    audioUrl: '/Music-Mp3/Music-C/未曾守护的梦.mp3',
    genre: '抒情',
    mood: 'melancholy',
    bpm: 80,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-008',
    title: '七秒之外',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1983.jpg',
    duration: 256,
    audioUrl: '/Music-Mp3/Music-C/七秒之外.mp3',
    genre: '流行',
    mood: 'energetic',
    bpm: 120,
    energy: 'high',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-009',
    title: '若善良已不见',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1990.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-C/若善良已不见.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 82,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-010',
    title: '一次就好',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1991.jpg',
    duration: 268,
    audioUrl: '/Music-Mp3/Music-C/一次就好.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 88,
    energy: 'medium',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-011',
    title: '撕碎星空的扉页',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1992.jpg',
    duration: 335,
    audioUrl: '/Music-Mp3/Music-C/撕碎星空的扉页.mp3',
    genre: '摇滚',
    mood: 'energetic',
    bpm: 138,
    energy: 'high',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'c-012',
    title: '河洛情韵',
    artist: '董小姐',
    album: '热血青春',
    albumCover: '/D-Music/D-98/Music-1993.jpg',
    duration: 288,
    audioUrl: '/Music-Mp3/Music-C/河洛情韵.mp3',
    genre: '古风',
    mood: 'calm',
    bpm: 72,
    energy: 'low',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
];

const ALBUM_D_SONGS: MusicSong[] = [
  {
    id: 'd-001',
    title: '98',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1994.jpg',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-D/98.mp3',
    genre: '流行',
    mood: 'happy',
    bpm: 98,
    energy: 'high',
    year: 1998,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-002',
    title: '那些年',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1995.jpg',
    duration: 245,
    audioUrl: '/Music-Mp3/Music-D/那些年.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 85,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-003',
    title: '不过时间而已',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1996.jpg',
    duration: 305,
    audioUrl: '/Music-Mp3/Music-D/不过时间而已.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 88,
    energy: 'medium',
    year: 2020,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-004',
    title: '若只如初见',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1997.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-D/若只如初见.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 82,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-005',
    title: '若善良真的已消失不见',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1978.jpg',
    duration: 345,
    audioUrl: '/Music-Mp3/Music-D/若善良真的已消失不见.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 75,
    energy: 'medium',
    year: 2021,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-006',
    title: '不懂的董小姐',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1979.jpg',
    duration: 312,
    audioUrl: '/Music-Mp3/Music-D/不懂的董小姐.mp3',
    genre: '民谣',
    mood: 'calm',
    bpm: 80,
    energy: 'medium',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-007',
    title: '热血摇滚',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1980.jpg',
    duration: 278,
    audioUrl: '/Music-Mp3/Music-D/热血摇滚.mp3',
    genre: '摇滚',
    mood: 'energetic',
    bpm: 145,
    energy: 'high',
    year: 2022,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-008',
    title: '男人的难',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1981.jpg',
    duration: 322,
    audioUrl: '/Music-Mp3/Music-D/男人的难.mp3',
    genre: '民谣',
    mood: 'melancholy',
    bpm: 78,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-009',
    title: '若善良已不见',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1982.jpg',
    duration: 298,
    audioUrl: '/Music-Mp3/Music-D/若善良已不见.mp3',
    genre: '流行',
    mood: 'melancholy',
    bpm: 82,
    energy: 'medium',
    year: 2023,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-010',
    title: '一次就好',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1983.jpg',
    duration: 268,
    audioUrl: '/Music-Mp3/Music-D/一次就好.mp3',
    genre: '抒情',
    mood: 'romantic',
    bpm: 88,
    energy: 'medium',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-011',
    title: '撕碎星空的扉页',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1990.jpg',
    duration: 335,
    audioUrl: '/Music-Mp3/Music-D/撕碎星空的扉页.mp3',
    genre: '摇滚',
    mood: 'energetic',
    bpm: 138,
    energy: 'high',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
  {
    id: 'd-012',
    title: '河洛情韵',
    artist: '董小姐',
    album: '初心不忘',
    albumCover: '/D-Music/D-98/Music-1991.jpg',
    duration: 288,
    audioUrl: '/Music-Mp3/Music-D/河洛情韵.mp3',
    genre: '古风',
    mood: 'calm',
    bpm: 72,
    energy: 'low',
    year: 2024,
    isOriginal: true,
    copyright: 'YYC³ 独家版权',
  },
];

const ALBUMS: AlbumConfig[] = [
  {
    id: 'album-a',
    name: 'Years Like Songs',
    nameZh: '岁月如歌',
    description: '董小姐首张个人专辑，收录14首原创歌曲，涵盖流行、民谣、抒情等多种风格',
    cover: '/D-Music/D-98/Music-1978.jpg',
    category: 'A',
    year: 2024,
    songs: ALBUM_A_SONGS,
  },
  {
    id: 'album-b',
    name: 'Floating Life',
    nameZh: '浮生如渡',
    description: '董小姐第二张专辑，以古风、抒情为主，讲述人生百态',
    cover: '/D-Music/D-98/Music-1990.jpg',
    category: 'B',
    year: 2024,
    songs: ALBUM_B_SONGS,
  },
  {
    id: 'album-c',
    name: 'Hot Blooded Youth',
    nameZh: '热血青春',
    description: '董小姐第三张专辑，融合摇滚、流行、古风，展现青春热血',
    cover: '/D-Music/D-98/Music-1980.jpg',
    category: 'C',
    year: 2024,
    songs: ALBUM_C_SONGS,
  },
  {
    id: 'album-d',
    name: 'Original Heart',
    nameZh: '初心不忘',
    description: '董小姐精选专辑，收录历年经典作品',
    cover: '/D-Music/D-98/Music-1995.jpg',
    category: 'D',
    year: 2024,
    songs: ALBUM_D_SONGS,
  },
];

const ARTIST: ArtistConfig = {
  id: 'dongxiaojie',
  name: 'Dong Xiao Jie',
  nameZh: '董小姐',
  avatar: '/D-Music/D-98/Music-1978.jpg',
  bio: '独立音乐人，YYC³签约艺人。以独特的嗓音和深情的演绎著称，作品涵盖流行、民谣、古风等多种风格。',
  albums: ['album-a', 'album-b', 'album-c', 'album-d'],
};

function getAllSongs(): MusicSong[] {
  return [...ALBUM_A_SONGS, ...ALBUM_B_SONGS, ...ALBUM_C_SONGS, ...ALBUM_D_SONGS];
}

function getSongsByMood(mood: MusicSong['mood']): MusicSong[] {
  return getAllSongs().filter((song) => song.mood === mood);
}

function getSongsByGenre(genre: string): MusicSong[] {
  return getAllSongs().filter((song) => song.genre === genre);
}

function getSongsByAlbum(albumId: string): MusicSong[] {
  const album = ALBUMS.find((a) => a.id === albumId);
  return album ? album.songs : [];
}

function getRandomSongs(count: number): MusicSong[] {
  const allSongs = getAllSongs();
  const shuffled = [...allSongs].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

function getRandomLogo(): string {
  return LOGO_IMAGES[Math.floor(Math.random() * LOGO_IMAGES.length)];
}

function getRandomPhoto(): PhotoConfig {
  return PHOTOS[Math.floor(Math.random() * PHOTOS.length)];
}

function getRecentPhotos(count: number): PhotoConfig[] {
  return [...PHOTOS].sort((a, b) => b.year - a.year).slice(0, count);
}

function getVideos(): VideoConfig[] {
  return VIDEOS;
}

export {
  LOGO_IMAGES,
  PHOTOS,
  VIDEOS,
  ALBUMS,
  ARTIST,
  ALBUM_A_SONGS,
  ALBUM_B_SONGS,
  ALBUM_C_SONGS,
  ALBUM_D_SONGS,
  getAllSongs,
  getSongsByMood,
  getSongsByGenre,
  getSongsByAlbum,
  getRandomSongs,
  getRandomLogo,
  getRandomPhoto,
  getRecentPhotos,
  getVideos,
};

export type { AlbumConfig, ArtistConfig, VideoConfig, PhotoConfig, MusicCategory };
